### Create a new player
POST http://localhost:3000/players
content-type: application/json

{
    "nickname": "SHiale"
}

### Get a particular player
GET http://localhost:3000/players/6936fae8022dfe70a898e5c6

### Get a undefined player.
GET http://localhost:3000/players/6as


### Get all players
GET http://localhost:3000/players